version: '3.5'

services:
  rust:
    container_name: rust-playground
    hostname: rust-playground-host
    build: .
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
    volumes:
      - data_rust_playground:/root/projects
volumes:
  data_rust_playground:
    name: rust-playground-data
    driver: local
