version: '3.5'

services:
  db:
    container_name: rust-playground
    hostname: rust-playground-host
    build: .
    volumes:
      - data_rust_playground:/root/projects
volumes:
  data_rust_playground:
    name: rust-playground-data
    driver: local
